

Error during exploration: 
Traceback (most recent call last):
  File "\\w2k16\abisync\data\testing\automseq\mseq_automation\testingprograms\ui_inspector2.py", line 45, in explore_mseq_app
    app.connect(title='mSeq', timeout=10)
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\site-packages\pywinauto\application.py", line 990, in connect
    self.process = timings.wait_until_passes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\site-packages\pywinauto\findwindows.py", line 84, in find_element
    elements = find_elements(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\site-packages\pywinauto\findwindows.py", line 273, in find_elements
    elements = [elem for elem in elements if elem.rich_text == title]
                                             ^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\site-packages\pywinauto\win32_element_info.py", line 83, in rich_text
    return handleprops.text(self.handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\site-packages\pywinauto\handleprops.py", line 92, in text
    buffer_ = create_unicode_buffer(length)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Local\miniconda3\Lib\ctypes\__init__.py", line 300, in create_unicode_buffer
    buf = buftype()
          ^^^^^^^^^
MemoryError
